### ISSUE TITLE
Proposal:  Add reasons for ERROR event

### ISSUE THREAD

**Issue by HaloFour** [michel-kraemer/actson#3]
It would be useful if when receiving the `JsonEvent.ERROR` event that there was a property set that could explain the reason why the parse failed.  Looking through the `JsonParser` source this seems like it would be simple enough to do since most error conditions are the result of an unexpected token.

I'd be happy to tackle this myself.

**Comment by michel-kraemer** [comment]
@HaloFour This sounds very interesting. Pull requests are very welcome.

If you like we can discuss the different values for this new property before you start implementing it.

**Comment by HaloFour** [comment]
Sounds good.  In keeping with the theme of `static final int` values to denote state I was considering the following:

```java
public interface JsonError {
  public static final int SUCCESS = 0;
  public static final int UNEXPECTED_EOF = 1;
  public static final int CHARACTER_CODING_EXCEPTION = 2;
  public static final int UNEXPECTED_CHARACTER_CLASS = 3;
  public static final int UNEXPECTED_END_OBJECT = 4;
  public static final int UNEXPECTED_END_ARRAY = 5;
  public static final int UNEXPECTED_START_OBJECT = 6;
  public static final int UNEXPECTED_START_ARRAY = 7;
  public static final int UNEXPECTED_COMMA = 8;
  public static final int UNEXPECTED_COLON = 9;
}
```

Then `JsonParser` would be updated to update/expose that value when an error occurs:

```java
private int error;

public int getJsonError() {
    return this.error;
}

// during parsing
event1 = JsonEvent.JSON_ERROR;
error = JsonError.UNEXPECTED_START_OBJECT;
```

I don't particularly like `JsonError.SUCCESS`.  An option could be to have `JsonParser::getJsonError` return an `Integer` which would be `null` but this project doesn't use boxing as a convention elsewhere and that feels like it would go against the grain.

I also have some concern that my chosen constants don't really convey enough information.  They indicate what tokens wouldn't be valid at that point in parsing but not the current state of the parser, although that should be implied by the tokens that had preceded it.  More apparent constants, e.g. `UNEXPECTED_END_ARRAY_IN_OBJECT` might seem cumbersome to work with.

Finally, while you track the number of parsed characters, how do you feel about also tracking the current line/column?  That could be as simple as checking the character when it is first read and incrementing the line count if it is `"\n"` otherwise incrementing the column count (and perhaps ignoring `"\r"`).
