### ISSUE TITLE
Support for unicode escapes

### ISSUE THREAD

**Issue by PetrGlad** [michel-kraemer/actson#4]
Unicode symbols represented as UTF-8 in strings are parsed as expected. I also see that parser has state `ES` (escape). But escapes of Unicode code-points are not converted to respective code points.
For example source text `"\"\\u00e9\"".getBytes()` is parsed as single token `"\\u00e9"` instead of `"é"`.

Here's the test ba58753276966227496d447dff6e9f0806b3a841

**Comment by PetrGlad** [comment]
I just looked at the source, it seem that end state of Unicode codepoint `u4`  should end with some action that parses the hex number. Or maybe codepoint state should be added to the stack to accumulate the number.

**Comment by PetrGlad** [comment]
I'll prepare a pull request. It seems that escapes are not properly handled in several places.

**Comment by michel-kraemer** [comment]
Thanks for spotting this. If you want to prepare a pull request please make sure Actson still achieves the same results (or better results) in the JSONTestSuite:
https://github.com/nst/JSONTestSuite

The JSONTestSuite tests against RFC 7159 compliance and not RFC 4627 which is out of date. See the following blog post for further information:
http://seriot.ch/parsing_json.php
