### ISSUE TITLE
Large string values

### ISSUE THREAD

**Issue by carr-james** [michel-kraemer/actson#44]
I am building an application that consumes large files of structured data and does some processing based on the content.
I'm using the Aalto streaming parser for XML files and this looks like the most similar option for JSON. 

One of the requirements for my project is that it must be able to handle large string values in the JSON, which may be too large to hold in memory. I'm wondering if there is any way I can use this parser in its current form to handle this case since as far as I can tell it only emits a VALUE_STRING JsonEvent once the parser has seen the closing `"`.

**Comment by michel-kraemer** [comment]
This is not possible at the moment but maybe I can find a clever way to implement a solution without changing the interface too much. Can you please describe your use case a little bit better? What do you want to do with the parsed large string if you cannot keep it in memory? Discard it? Write it to disk?

**Comment by carr-james** [comment]
I'm writing a program that splits down large files into smaller components based on a tree-like hierarchy. 

One of the requirements is that we may encounter different file types nested within one another, e.g. a json file that has a string field that contains a large xml document.

**Comment by michel-kraemer** [comment]
I've just released a new version 2.1.0 that allows you to provide a custom implementation of a character buffer to control how many bytes of the currently parsed value you want to keep in memory. See the following unit test for an example:
https://github.com/michel-kraemer/actson/blob/2df59298d68b0eaf3d19b9ccf9e52f5703ea824e/src/test/java/de/undercouch/actson/JsonParserTest.java#L437-L480

With this new feature, you have the following possibilities to implement what you need:
* Keep track of the characters in your custom buffer and flush the buffer if it gets too large
* Stop feeding bytes to the parser with `JsonParser.getFeeder().feed()` if your buffer is too large and you need to cope with the amount of data first

Be aware that methods such as `JsonParser.getCurrentString()` or `JsonParser.getCurrentInt()` depend on the contents of your buffer. If you flush it during parsing, these methods may return incomplete values.

**Comment by michel-kraemer** [comment]
Let me know if this helps or if you need anything else. Thanks.

**Comment by carr-james** [comment]
Thank you very much, this looks very promising!
