### ISSUE TITLE
Streamline API, remove feeder.

### ISSUE THREAD

**Issue by PetrGlad** [michel-kraemer/actson#6]
I am thinking about getting rid of other validating legacy of thins code. Procedures that use feeder look cumbersome (see these loops in d.u.a.JsonParserTest#parseFail, for example). So removing feeder from parser altogether should simplify code and it's usage. Looking at d.u.a.JsonParser#nextEvent I now think that whole point of having feeder is the ability to detect premature end of input and return EOF or ERROR events appropriately. Application that is only interested in parsing still can trivially infer these conditions anyway. Here's changes that I propose.
Change API of parser to 
```java
public class JsonParser {
  public JsonParser(int depth) {...} // Initial state, only constructor
  public int getMaxDepth() {...} // Keep this
  public int nextEvent(char nextChar) {...} // Change state with next input text's character, return event. 
  // All else would be non public or removed
}
```
This effectively reduces parser to be state machine only. This keeps input buffering out of parser so clients are free to use whatever they want without implementing interface. 

Replace event EOF with, say, END which is emitted when current JSON structure is completely parsed. This happens when we have already parsed a scalar value or end of nested structure is popped and stack is empty.
Here are 2 options: after issuing END all subsequent calls would produce ERROR which is similar to current behavior, or keep parsing as we're at the beginning. In case when sequence of multiple JSON documents is expected in input first option would require to re-create parser to parse new piece, later case allow to reuse it and just interpret END event if necessary. Since I am interested in this use-case I'd prefer to keep parsing after END. 

`setDepth` setter should be removed since it is not clear what to do if we are in the middle of parsing, say, at depth 100 and this setting is changed to 50.

The parser usage example would be like:
```java
final JsonParser jsonParser = new JsonParser(100);
final CharSequence jsonSource = "{\"abc\":123}";
int i = 0;
int event;
while (i < jsonSource.length()) {
    event = jsonParser.nextEvent(jsonSource.charAt(i++));
    if (event != NEED_MORE_INPUT) {
      // One can handle END event explicitly here, e.g. break loop 
      processEvent(event);
    }
}
if (event == NEED_MORE_INPUT) {
   throw new RuntimeError("Incomplete JSON input.");
}
```

**Comment by michel-kraemer** [comment]
Thanks for the feedback. The idea looks very promising indeed. However, you still have to do the buffering anywhere. Look at the following example:
https://github.com/michel-kraemer/actson/blob/master/examples/src/main/java/rxjava/JsonParserOperator.java

How would you implement this operator with the changes you propose? It actually is possible to implement the same behaviour but you would have to move the buffering from the feeder to the operator, so in fact you're moving the responsibility to the caller.

**Comment by PetrGlad** [comment]
I did not work with rxJava so I'll experiment with it. However general idea is that UTF-8 decoder should be a separate step in pipeline.

**Comment by HaloFour** [comment]
I agree that the feeder interface is a little cumbersome.  I'm thinly wrapping Grizzly's NIOReader and the `feed` overloads are just noise.  But I prefer the source aspects of that interface to having to feed individual characters to `JsonParser` in a loop.

**Comment by PetrGlad** [comment]
I pondered over alternatives, one could be to move that feed-while/read-while loops inside feeder so all UTF-8 decoding is in it's own class independent from JSON decoder. Other is to have completely asynchronous UTF-8 decoder that is written similarly to JSON parser so it gets bytes one-by one and then calls JSON parser when whole new char is available. I think that own parser would produce simpler code overall compared to working around java.nio.Buffer and CharDecoder quirks.

**Comment by PetrGlad** [comment]
I'll close it for now. I initially misunderstood the purpose of feeder, which is to decode byte stream into char stream. Also not I see cases when we do need to tell parser that end of stream is reached e.g. on input "123" one cannot tell whether it's 123 or first digits of a longer number.

I have a version of suggested API here https://github.com/PetrGlad/actson/blob/simple-api/src/main/java/de/undercouch/actson/JsonParser.java#L374 See functions `JsonParser#nextInput` and `JsonParser#endInput` and their usages (e.g. here https://github.com/PetrGlad/actson/blob/simple-api/src/test/java/de/undercouch/actson/JsonHelper.java#L37)
